//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace symphony_limited.FrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academy
    {
        public int AcademyId { get; set; }
        public string PeopleManageme { get; set; }
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Fanpage { get; set; }
        public string ImgAcademy { get; set; }
        public string description { get; set; }
    }
}
